export const BRANCH_FETCH_START = 'BRANCH_FETCH_START';
export const BRANCH_FETCH_SUCCESS = 'BRANCH_FETCH_SUCCESS';
export const BRANCH_FETCH_FAILURE = 'BRANCH_FETCH_FAILURE';


export const BRANCH_ADD_START = 'BRANCH_ADD_START';
export const BRANCH_ADD_SUCCESS = 'BRANCH_ADD_SUCCESS';
export const BRANCH_ADD_FAILURE = 'BRANCH_ADD_FAILURE';


export const BRANCH_UPDATE_START = 'BRANCH_UPDATE_START';
export const BRANCH_UPDATE_SUCCESS = 'BRANCH_UPDATE_SUCCESS';
export const BRANCH_UPDATE_FAILURE = 'BRANCH_UPDATE_FAILURE';


export const BRANCH_DELETE_START = 'BRANCH_DELETE_START';
export const BRANCH_DELETE_SUCCESS = 'BRANCH_DELETE_SUCCESS';
export const BRANCH_DELETE_FAILURE = 'BRANCH_DELETE_FAILURE';


export const BRANCH_USERS_FETCH_START = 'BRANCH_USERS_FETCH_START';
export const BRANCH_USERS_FETCH_SUCCESS = 'BRANCH_USERS_FETCH_SUCCESS';
export const BRANCH_USERS_FETCH_FAILURE = 'BRANCH_USERS_FETCH_FAILURE';