export const CLIENT_FETCH_START   = 'CLIENT_FETCH_START';
export const CLIENT_FETCH_SUCCESS = 'CLIENT_FETCH_SUCCESS';
export const CLIENT_FETCH_FAILURE = 'CLIENT_FETCH_FAILURE';

export const CLIENT_ADD_START     = 'CLIENT_ADD_START';
export const CLIENT_ADD_SUCCESS   = 'CLIENT_ADD_SUCCESS';
export const CLIENT_ADD_FAILURE   = 'CLIENT_ADD_FAILURE';

export const CLIENT_UPDATE_START   = 'CLIENT_UPDATE_START';
export const CLIENT_UPDATE_SUCCESS = 'CLIENT_UPDATE_SUCCESS';
export const CLIENT_UPDATE_FAILURE = 'CLIENT_UPDATE_FAILURE';

export const CLIENT_DELETE_START   = 'CLIENT_DELETE_START';
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS';
export const CLIENT_DELETE_FAILURE = 'CLIENT_DELETE_FAILURE';
