export const EVENT_FETCH_START = 'EVENT_FETCH_START';
export const EVENT_FETCH_SUCCESS = 'EVENT_FETCH_SUCCESS';
export const EVENT_FETCH_FAILURE = 'EVENT_FETCH_FAILURE';

export const EVENT_ADD_START = 'EVENT_ADD_START';
export const EVENT_ADD_SUCCESS = 'EVENT_ADD_SUCCESS';
export const EVENT_ADD_FAILURE = 'EVENT_ADD_FAILURE';

export const EVENT_UPDATE_START = 'EVENT_UPDATE_START';
export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS';
export const EVENT_UPDATE_FAILURE = 'EVENT_UPDATE_FAILURE';

export const EVENT_DELETE_START = 'EVENT_DELETE_START';
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAILURE = 'EVENT_DELETE_FAILURE';
