export const FETCH_ROLES_START = 'FETCH_ROLES_START';
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const FETCH_ROLES_FAILURE = 'FETCH_ROLES_FAILURE';

export const FIND_ROLE_START = 'FIND_ROLE_START';
export const FIND_ROLE_SUCCESS = 'FIND_ROLE_SUCCESS';
export const FIND_ROLE_FAILURE = 'FIND_ROLE_FAILURE';

export const ROLE_ADD_START = 'ROLE_ADD_START';
export const ROLE_ADD_SUCCESS = 'ROLE_ADD_SUCCESS';
export const ROLE_ADD_FAILURE = 'ROLE_ADD_FAILURE';

export const ROLE_UPDATE_START = 'ROLE_UPDATE_START';
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS';
export const ROLE_UPDATE_FAILURE = 'ROLE_UPDATE_FAILURE';

export const ROLE_DELETE_START = 'ROLE_DELETE_START';
export const ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';
export const ROLE_DELETE_FAILURE = 'ROLE_DELETE_FAILURE';

export const CLEAR_SELECTED_ROLE = 'CLEAR_SELECTED_ROLE';
