export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const VIEW_PROFILE_START = 'VIEW_PROFILE_START';
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS';
export const VIEW_PROFILE_FAILURE = 'VIEW_PROFILE_FAILURE';

export const LOGOUT = 'LOGOUT';
